### ISSUE TITLE
only get an error when the home directory has not the .npmrc file.

### ISSUE THREAD

**Issue by DeandreFu** [fujia-cli/stage#21]
Hey! when I run the follows commands and get the error:

`
PS C:\Users\MI> stage
[stage] info Thanks to use @fujia/stage(version: 1.3.3)^_^
[stage] ERR! [cli-core] the path of C:\Users\MI\.npmrc is not exist
`
I think it because of  there is not the .npmrc file in the home dir. 

In fact, It's okay when I created the corresponding file. 

However, I don't think this is an expected behavior!

**extra information as follows:**
 - OS: win11
 - Terminal: PowerShell

![image](https://user-images.githubusercontent.com/100774365/156499924-ca5ef843-ef52-4cb9-86d9-e638b5490327.png)

**Comment by fushenguang** [comment]
@DeandreFu the issues has been fixed in V1.3.4.
