### ISSUE TITLE
It's okay but get an unknow error information when run the command "stage docker"

### ISSUE THREAD

**Issue by DeandreFu** [fujia-cli/stage#23]
It's okay but get an unknow error information when run the command "stage docker", more as follows:

`
[stage] info The @fujia/cli-docker package install failed. the errors: ENOENT: no such file or directory, scandir 'C:\Users\MI\.stage-cli\caches\node_modules\_@fujia_cli-docker@1.3.4@@fujia\cli-docker\template'
[stage] info Thanks to use @fujia/stage(version: 1.3.4)^_^
`

**extra information as follows:**

OS: win11
Terminal: PowerShell
stage version: 1.3.4

**Screenshots**

![errors](https://user-images.githubusercontent.com/100774365/157002196-d7ac15be-81f2-411b-a50f-29a947dff19b.jpg)

**Comment by fushenguang** [comment]
@DeandreFu the issue has been fixed in version 1.3.5.
